# Generated by Django 3.2.15 on 2023-08-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecompare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLogTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jlrq', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('source_data', models.CharField(max_length=255, verbose_name='源数据')),
                ('now_data', models.CharField(max_length=255, verbose_name='现数据')),
                ('exec_sql', models.CharField(max_length=255, verbose_name='执行的sql')),
                ('plan_id', models.IntegerField(verbose_name='执行方案id')),
            ],
            options={
                'verbose_name': '同步日志',
                'db_table': 'SyncLogTable',
            },
        ),
        migrations.AlterField(
            model_name='syssynctable',
            name='zxrq',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行日期'),
        ),
    ]
