# Generated by Django 3.2.15 on 2023-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysSyncTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='方案名称')),
                ('jlrq', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立日期')),
                ('zxrq', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行日期')),
                ('ty', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否停用')),
                ('bz', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '同步数据库方案主模型22',
                'db_table': 'SysSyncTable',
            },
        ),
        migrations.CreateModel(
            name='SysSyncTableDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_id', models.IntegerField(blank=True, null=True, verbose_name='方案id')),
                ('table_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='表名称')),
                ('sync_field', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否同步字段')),
                ('sync_data', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否同步数据')),
                ('sync_index', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否同步索引')),
                ('bz', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '同步数据库方案明细',
                'db_table': 'SysSyncTableDetail',
            },
        ),
    ]
