# Generated by Django 3.2.15 on 2023-08-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecompare', '0002_auto_20230824_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclogtable',
            name='recover_sql',
            field=models.CharField(default=1, max_length=255, verbose_name='还原的sql'),
            preserve_default=False,
        ),
    ]
