# Generated by Django 3.2.15 on 2023-08-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablecompare', '0003_synclogtable_recover_sql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclogtable',
            name='now_data',
        ),
    ]
