# Generated by Django 3.2.15 on 2023-08-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecompare', '0004_remove_synclogtable_now_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclogtable',
            name='plan_id',
            field=models.IntegerField(null=True, verbose_name='执行方案id'),
        ),
    ]
