# Generated by Django 3.2.15 on 2023-09-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecompare', '0005_alter_synclogtable_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclogtable',
            name='table_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='表名称'),
        ),
    ]
